DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS VOTERS;

CREATE TABLE VOTERS (
    voterId VARCHAR(250) NOT NULL  PRIMARY KEY,
    voterName VARCHAR(250) NOT NULL,
    voterPassword VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS VOTERMAP;

CREATE TABLE VOTERMAP (
    voterId VARCHAR(250) NOT NULL,
    electionId VARCHAR(250) NOT NULL,
    isVoterEligible BIT DEFAULT true,
    isVoterAdmin BIT default false
);

DROP TABLE IF EXISTS ELECTION;

CREATE TABLE ELECTION (
    electionTitle VARCHAR(250) DEFAULT 'New Election',
    electionId VARCHAR(250) NOT NULL PRIMARY KEY,
    electionDescription VARCHAR(250) DEFAULT 'Election Description',
    adminVoterId VARCHAR(250) NOT NULL,
    postSetId VARCHAR(250) NOT NULL
);